### ISSUE TITLE
How is hf different from fzf?

### ISSUE THREAD

**Issue by Hunter-Github** [hugows/hf#2]
https://github.com/junegunn/fzf - is your project a fork, a re-implementation, what are the main differences? The UI looks pretty much the same.

**Comment by baileyn** [comment]
One thing I've noticed is that hf installed, and also worked perfectly, on Windows for me. I don't believe that fzf supports Windows, and if it does it really doesn't explain installation in the README. I tried the way they mention installing it from git, and it requires a "linux environment" for the install script. I attempted to "go get" it after that, and it complained about needed "curses.h."  If nothing else, I would assume hf is at the very least more windows-friendly.

**Comment by hugows** [comment]
I just never knew fzf existed. So I'd say its an alternate implementation, much less mature, much smaller in scope, and based on termbox-go instead of curses.

I actually asked junegunn how he does the fuzzy matching, and probably will try it on hf. I see no reason to delete my project now, since it works well for me, and works on Windows too (which I use at work). 
I'll update the README to list the alternatives.
